hostname: fritz.box

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous

logging:
  enabled: false

monitoring:
  enabled: true

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 5Gi

addons:
  argocd:
    enabled: true
  authservice:
    enabled: true
  haproxy:
    enabled: true
      git:
    path: ./chart
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/developer-tools/haproxy
    tag: 1.1.2-bb.0
  values: {}
