hostname: bb.fritz.box

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous

logging:
  enabled: false

monitoring:
  enabled: true

twistlock:
  enabled: false
  values:
    console:
      persistence:
        size: 5Gi

addons:
  authservice:
    enabled: false
  gitlab:
    enabled: true
  haproxy:
    enabled: true
