apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:uTH/D0Y4glR1gzhlz/zgbo5Su1ZlHD4b+0gfwdPVi0ZcCtiwk1GZjnB6q/+/gWkr9Dp8tsPYws3wL7hexHRnVO8nbwdOul4LCXnxpnBarXHxBcGeJnyGPgm0VO/8KhX4OYNdD65FNFqXiWvgFirTEDy9yYhhsbwsCiHW0WG/ziL/I3jT6T5bXJa5Ihsp6QQvbeYtNk+IV2tK49f4hj8E2mrRQIJZ/lCbXbccewIHbg0ekblfFMM8GiGpA3DBMLCMM6TcC/gsB+EcQrKERdfPx/9fu3iIyHQt0dSi6Vb8xM2tN1xB77ClzxV4MFvA4k6lNNkcwdP+5LhBp9UlwJBdMCQZdk2o9XO9/39kpKtybW8vlB500X6rjK//GPdFi0DwmAY1uhmDorvqjA646Q9zfdxNEOjFssxOoO/kQz2nSRX2pW8t5gosDYwzSZsWyXyUscMwBpgJHcswayjTKVNTRyK6jn5zk6S2DM1xfjkBRw5PkQtK56mdPww3WEuz/+tXKNVdpyMszx1Vg5L10R3uNQyt/2xy+nx2fDnNBV/0NZyqw64UVnlI64ekarRFvazgNLeiLiMrM92WrW3RYQ7o7yLunTunTdjOEljGanE2yuOZp7XnlBUrN2F1l4DvAj4DS0kqofqtY/oaTc/EwZLhwMnboJazrMGv51sL7ZqfeNCnrNLWyNiPOXrGghKm1N7eaY7/Mlc6DH78nXQ0YuQCfmZ/1fls/ztBDn0=,iv:UElH0VT30Kp4NYMt+d3iLCn2d/gHUGMRbGfaUKtAaO4=,tag:hjChmFEM01vCBh6ivOruTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-29T15:49:33Z'
    mac: ENC[AES256_GCM,data:ZpMYWZ0fm6paSYxJPiVPqkjPsPq1V+LXB0OaTe+crcJZTI0uHoY2MtfiKPhc96C4g+LteAzxXh7WuQFNjBXjqC9Qvr8ZQm/nOAjwri6ug00sp65rOC06sgpbBHipgH5/+zcf56HgETHn9jo0IB4oHYrFyvNo7Qh7SAQh9CTlthw=,iv:25gzeUszkyKF7scR7XHQ+UyfdLHV9qausSmZd7o3/W4=,tag:QMJ7XHSyyIdEIggZfQ36Hw==,type:str]
    pgp:
    -   created_at: '2020-11-17T04:12:34Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA93W3Fi3CqSYARAAkxXH58DZwkKS++G0k6meSbJJqj/Ai1vh7W2jP17KTHbl
            I2sPuTv9PfrorBoWMKz8witmnjHy7QKspxwl5+YWgwFZ0ESIwt/ArKhYqwyPGilz
            MLZ4cbsYyQZIHlnvoZYFeSJ0Blx1CmwG6LxTDjw0hupM38/p6U5Dkmuohq09GGJW
            JskA3ROKxAbXmw+vOm/qihDw3WgCQ02EShQpSzXoUzIklPgjHOxkCyVxHoOajba2
            WuueDbomOBan0vdfQFaLKhdPLSDfXf2KBnyEAqPWQ2zvF8T3nR8RFUvPtdg2FmO8
            H/+xF3//Jo4iTh1DjdRVpMdlM8qyhXdS1GpF86p6Ki6vjq2+eltnIPzIIg0KWlNp
            5qKGsOjr1m02x43pVLm537VFZrKJDobHZSsxVmtDk/TdyEa70FcQ2VlHX4k6mA9j
            KgxLJi++qKNx1nf+9ok1EzR4rN1pA7TjL2edLxFSiXHmfGl0oPz7PY/3pEG1q7qz
            ZWVJ3IAxxoq38jkqrtvlpOQGkv7isNAMbTWh45mSGeHUEPw7UzdssTwKh78r1V1E
            qarUuFxx6JlZCkPB/dJCnxot80CSuP9hc5eyvwveFP2KnKZi2Pst4nGmR4xKNCdd
            EwlmjI0WMXqSVmNlxK6EAWr3EvbMH5WrUeaQxrqvOHQfCPWH+pkJY1RGe1mHXFLS
            XgH4OwwYNd0kwxDKcJFhYl2QTWHwjoG8+Bo3nkR/W39+tyV/O0AzqlBm89c1+WJn
            VMUBiGmTXrl6GJfpHz3daAXOUAks8eGgXCGTd/xtdrbgtpZBOe6bAbJ9kDOBJno=
            =G/FT
            -----END PGP MESSAGE-----
        fp: 41BFF8BAF2586039F6293D835A2E820C25FE527C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
